### PR TITLE
Allow Solidus v3

### PR DESCRIPTION
**Pull request by afdev82**
Allow to install along with Solidus v3

### CODE REVIEW

**Review by tvdeyen — APPROVED** [review]
4.0 is very optimistic 😅

But totally fine. Thanks.

**Comment by tvdeyen** [comment]
Would you mind to add 3.0 as branch on the ci as well?

**Comment by afdev82** [comment]
> Would you mind to add 3.0 as branch on the ci as well?

Do you mean [here](https://github.com/AlchemyCMS/alchemy-solidus/blob/3a9438c452becb5a42c7c5539c22236c8e69484a/.github/workflows/ci.yml#L24)?

**Comment by tvdeyen** [comment]
Yes

**Comment by afdev82** [comment]
I don't know exactly why the tests are failing... I found this change in the solidus repo: https://github.com/solidusio/solidus/commit/f04c1317d656526b63f802b8770db17275de8409#diff-37d0229a61fc9ce26db97dacb2850bf28c65d7a3e4c6b7b1ed70d798eb1d13a8
I don't know if it could be related.
The problem I think is that the Spree.user_class is not set in the tests.
I found some fixes in the lib regarding the Spree user and the install generator, I don't know if they are related too.

**Comment by tvdeyen** [comment]
@afdev82 a rebase with latest `main` branch should fix some of the build issues

**Comment by afdev82** [comment]
I'm on Alchemy v5.2.1.
If I try this branch, my app crashes.
I opened the issue https://github.com/AlchemyCMS/alchemy-solidus/issues/79

**Comment by afdev82** [comment]
I think the failure in the build is not related with my change.

**Comment by tvdeyen** [comment]
@afdev82 you are right they were caused by an update of Gutentag. I just merged a fix. Rebasing should fix your builds

**Comment by hrdchz** [comment]
Looks like this has some pending checks but should be fine?

**Comment by afdev82** [comment]
I'm using that in production and it's fine.

**Comment by hrdchz** [comment]
> I'm using that in production and it's fine.

Thank you. I should have clarified my comment: "... should be fine to approve once these checks are clear"

**Review by tvdeyen — APPROVED** [review]
@afdev82 do you mind to rebase and force push again? Not sure why GitHub is not picking up.

**Pull request merged**
