### PR TITLE
Update dependencies to Solidus 2.0 and Alchemy 4.0

### PR DESCRIPTION
**Pull request by tvdeyen**
Allows to install latest Solidus and Alchemy 4.0.0.beta

### CODE REVIEW

**Comment by afdev82** [comment]
Any plan of when this will be merged into master?
Thank you.

**Comment by afdev82** [comment]
I think it would be better to require the single gems (backend, core, etc) instead of the solidus one.  
Because then I could avoid to install not needed components (like the gem for samples in production).
What do you think?

**Comment by tvdeyen** [comment]
Good catch @afdev82

Will change that

**Comment by tvdeyen** [comment]
Closed in favour of #16

**Pull request closed without merging**
